language: python
env:
  matrix:
  - PYTHON="python=2.7"
  - PYTHON="python=3.4"
  global:
  - GH_REF: github.com/biorack/metatlas.git
  - secure: HCQ8gC9b17rPuF4/KnZFlh3crLhlRFKtbUMVJGFuCnz4r7Zna1TELWgmLI0WX6jGgwjjO9ca5aKOOKj0CVGvOPTmIX3VCGEehgxfN0K9pdE9eUlaN047hh32CrTxtik97jxImvPnbni/QmwI3/xI/XrPj2U5iUm38h/WDg+sTPU=
  - METATLAS_LOCAL: 1
before_install:
# - sudo apt-add-repository "deb http://cran.stat.ucla.edu/bin/linux/ubuntu trusty/"
# - sudo apt-get update
# - sudo apt-get install --force-yes libnetcdf-dev netcdf-bin r-base
- export MPL_DIR=$HOME/.config/matplotlib
- mkdir -p $MPL_DIR
- touch $MPL_DIR/matplotlibrc
- echo "backend:Template" > $MPL_DIR/matplotlibrc
- wget -nv http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes
- conda update conda -q
- conda info -a
- conda create --quiet --yes -n test $PYTHON pip nose pytables matplotlib pandas jupyter h5py
- source activate test
# - rm /home/travis/miniconda/envs/test/lib/libreadline.so.6
- Miniconda-latest-Linux-x86_64
# rpy2
# - sudo Rscript scripts/xcms-install.R
- conda install -c https://conda.anaconda.org/rdkit rdkit
install:
#- export PYTHONWARNINGS=all
- pip install -e .
script:
#- export METATLAS_LOCAL=1
- if [[ $PYTHON == python=3.4* ]]; then nosetests --exe -v --with-doctest --with-cov
  --cover-package metatlas; else nosetests --exe -v metatlas; fi
- make docs
after_success:
- coveralls
- if [[ $PYTHON == python=3.4* ]]; then bash scripts/travis_after_success.sh; fi
